// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opmnneryubzifmhtxgss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbW5uZXJ5dWJ6aWZtaHR4Z3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODExMzcsImV4cCI6MjA2NTY1NzEzN30.xr0PkVNhfkZNXiwV3y2gM6RahowqI_FAoH9QO16OUfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);